name: Snorby
description: |
 Snorby is a ruby on rails web application for network security monitoring that interfaces with current popular intrusion detection systems (Snort, Suricata and Sagan). The basic fundamental concepts behind Snorby are simplicity, organization and power. The project goal is to create a free, open source and highly competitive application for network monitoring for both private and enterprise use.
version: 2.6.2
category: ids
maintainer: # The maintainer of the catalog entry
license: GNU General Public License
projectURL: https://github.com/Snorby/snorby